import = ["~/.config/alacritty/dracula.toml"]
live_config_reload = true

[font]
size = 9.0

[selection]
save_to_clipboard = true

[window]
title = "hi"
# decorations = "None"

[window.dimensions]
columns = 250
lines = 60

[window.padding]
# x = 10
# y = 10
x = 0
y = 0

[shell]
program = "/bin/zsh"
args = ["-c", "zellij attach --index 0 || zellij"]
